#server.port=8761
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.default-zone=http://$microservices.svc.cluster.local:8761/eureka
#eureka.instance.hostname=localhost
#eureka.instance.appname=eurikaserver

eureka:
  instance:
    appname: eurikaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://microservices-eurikaserver-deployment-0.eurikaserver.microservices.svc.cluster.local:8761/eureka/

server:
  port: 8761